runtime: go124
service: default

# Conexión a Cloud SQL — dev
beta_settings:
  cloud_sql_instances: loopi-dev-497600:us-central1:loopi-db-dev

env_variables:
  ENV: dev
  GCP_PROJECT: loopi-dev-497600
  APP_VERSION: "1.0.0"
  OTEL_SERVICE_NAME: "loopi-api"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
